### ISSUE TITLE
Deploying Anno4j in a servlet

### ISSUE THREAD

**Issue by ghost** [anno4j/anno4j#121]
Hi i tried to deploy a anno4j example in tomcat8 with java8 after to build the maven project. However i'm receiving the below exception when i do some request to the server side (anno4j):

```
03-Feb-2017 19:04:04.145 SEVERE [http-nio-8080-exec-3] org.apache.catalina.core.ApplicationContext.log Exception while dispatching incoming RPC call
 com.google.gwt.user.server.rpc.UnexpectedException: 
Service method 'public abstract java.lang.String anno4j.test.client.GreetingService.greetServer(java.lang.String) throws java.lang.IllegalArgumentException' 
**threw an unexpected exception: java.lang.NoSuchMethodError: org.openrdf.sail.memory.MemoryStore.setSupportedIsolationLevels([Lorg/openrdf/IsolationLevel;)V**
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: **org.openrdf.sail.memory.MemoryStore.setSupportedIsolationLevels([Lorg/openrdf/IsolationLevel;)V
	at org.openrdf.sail.memory.MemoryStore.<init>(MemoryStore.java:136)
	at com.github.anno4j.Anno4j.<init>(Anno4j.java:82)**
	at anno4j.test.server.GreetingServiceImpl.greetServer(GreetingServiceImpl.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	... 27 more


```

PS: Using the command line i'm able to get the result for anno4j. What could be the possible solutions to it? Someone else tried to deploy the project in a servlet?
Best,
Silvio

**Comment by berndl** [comment]
Hi @silviodc !
Sorry I did not answer in time. It seems like you have resolved your issue on your own?

The Anno4j library does not (yet) have a web component to it.
We are planning to do that, but it is a goal for the long run, so it won't be available to soon I am afraid.

Would you mind giving us some insights on what you have done? We would be happy to learn some things from what you have experimented with! :)

Best,
Manu

**Comment by ghost** [comment]
Hi @berndl 
In fact the anno4j project works well! ;)

In my project i'm combining anno4j annotations to owl:class and using semantic distance between classes to retrieval useful information.

The problem was different sesame versions in the project [Slib](https://github.com/silviodc/slib) (Where i was calculating the semantic distance)
After i updated the sesame version it worked!
