### ISSUE TITLE
Testing generated Java files

### ISSUE THREAD

**Issue by fischmat** [anno4j/anno4j#129]
For testing that the Java files generated by the RDFS parser are valid, the following procedure was followed:

1. Generate the files using the `RDFSJavaFileGenerator`
2. Build and package Anno4j as a JAR with dependencies (if such a JAR does not exist)
3. Compile the generated files with Anno4j JAR in user classpath
4. Compile the actual test with Anno4j JAR and previously compiled `.class` files in user classpath
5. Instantiate and run the actual test using Java reflection

But when resource objects are instantiated with Anno4j in the actual test, an exception is thrown:
```
java.lang.ClassCastException: Cannot cast resource urn:anno4j:BLANK to a de.example.Car
	at org.openrdf.repository.object.ObjectFactory.createObject(ObjectFactory.java:166)
	at com.github.anno4j.Transaction.createObject(Transaction.java:203)
	at com.github.anno4j.Anno4j.createObject(Anno4j.java:324)
	at com.github.anno4j.Anno4j.createObject(Anno4j.java:317)
	at com.github.anno4j.Anno4j.createObject(Anno4j.java:296)
	at runtime.VehicleOntologyRuntimeTest.testAnno4j(VehicleOntologyRuntimeTest.java:104)
	at runtime.VehicleOntologyRuntimeTest.run(VehicleOntologyRuntimeTest.java:20)
	... 34 more
Caused by: java.lang.ClassCastException: Cannot cast object.proxies._fffffffff6fcf60f._EntityProxyffffffff9de06bd4 to de.example.Car
	at java.lang.Class.cast(Class.java:3369)
	at org.openrdf.repository.object.ObjectFactory.createObject(ObjectFactory.java:162)
	... 40 more
```
is caused by the following snippet of code:
```java
import de.example.Car; // Previously compiled and loaded before compilation of this class

Anno4j anno4j = new Anno4j();
Car myCar = anno4j.createObject(Car.class); // <-- Exception thrown here
```

**Comment by fischmat** [comment]
The current workaround for this is to also compile and load an implementation for the support classes in step 4, which simulates the behaviour of Anno4j.
This way some requirements like XSD validation code and proper handling of superproperties can be tested.

**Comment by fischmat** [comment]
As it seems the `javac` command is not available during Travis CI building.
Thus it is questionable whether such a test with compilation makes sense.

**Comment by fischmat** [comment]
The test can be prevented from running on systems without `javac` or Maven by using [JUnit Assume](http://junit.sourceforge.net/javadoc/org/junit/Assume.html).
In the tests `@Before` method the above programs are checked and the test is ignored if any of them is not present.
Thus the test is skipped on Travis CI, but not when running all tests from a local machine.

**Comment by fischmat** [comment]
The test described above will become obsolete because of schema handling logic (especially `rdfs:subClassOf`) will be moved to an intermediate support-class `SchemaSanitizingSupport` (see issue #135 ).
This class requires Anno4j functionality, which can't be used in a live loaded test (s.a.).
