### ISSUE TITLE
[QueryService] Search using a URI 

### ISSUE THREAD

**Issue by papadako** [anno4j/anno4j#50]
It seems that searching using a URI does not work as expected.

Assume that I want to get all annotations that have as body a specific resource. I guess I would have to use something like

``` java
queryService.setAnnotationCriteria("oa:hasBody", uri).execute();
```

If the string of the uri is of the form "http://domain.com/entity/annotations/bodies/061f499e-c93d-4268-af91-55865e597f34" I get an exception. It seems that since this is a URI it accepts a URI in the form <URI>. The exception is given below.

```
Caused by: org.openrdf.rio.RDFParseException: Expected '<' or '_', found: @ [line 1]
    at org.openrdf.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:441)
    at org.openrdf.rio.helpers.RDFParserBase.reportFatalError(RDFParserBase.java:671)
    at org.openrdf.rio.ntriples.NTriplesParser.reportFatalError(NTriplesParser.java:613)
    at org.openrdf.rio.ntriples.NTriplesParser.parseSubject(NTriplesParser.java:350)
    at org.openrdf.rio.ntriples.NTriplesParser.parseTriple(NTriplesParser.java:282)
    at org.openrdf.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:193)
    at org.openrdf.http.client.BackgroundGraphResult.run(BackgroundGraphResult.java:133)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

On the other hand if I use as the uri string the following  "http://domain.com/entity/annotations/bodies/061f499e-c93d-4268-af91-55865e597f34" I get no results...

Checking  the finally constructed SPARQL query in Virtuoso 

```
SELECT  ?annotation
WHERE
  { ?annotation <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/oa#Annotation> .
    ?annotation <http://www.w3.org/ns/oa#hasBody> ?var1
    FILTER regex(str(?var1), "http://domain.com/entity/annotations/bodies/061f499e-c93d-4268-af91-55865e597f34", "")
  }
```

returns the correct results, while "<http://domain.com/entity/annotations/bodies/061f499e-c93d-4268-af91-55865e597f34 >"

```
SELECT  ?annotation
WHERE
  { ?annotation <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/oa#Annotation> .
    ?annotation <http://www.w3.org/ns/oa#hasBody> ?var1
    FILTER regex(str(?var1), "<http://domain.com/entity/annotations/bodies/061f499e-c93d-4268-af91-55865e597f34>", "")
  }
```

does not.

**Comment by papadako** [comment]
I finally resolved this. It seems this is a bug with Virtuoso 7.1.0. I installed Virtuoso 7.2.1 and I get no exception. I guess it was related to https://github.com/tinkerpop/blueprints/issues/464
