### ISSUE TITLE
Cast problems when creating annotations from json-ld

### ISSUE THREAD

**Issue by papadako** [anno4j/anno4j#63]
For example adding a motivation to the JSONLD object in the InputOutputTest like this one

```
+ " \"oa:motivatedBy\":\"oa:describing\" , \n"
```

leads to the following exception:

```
java.lang.ClassCastException: http://www.w3.org/ns/oa#describing cannot be cast to com.github.anno4j.model.Motivation
    at org.openrdf.repository.object.advisers.PropertyBehaviour.intercept(PropertyBehaviour.java:146)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.openrdf.repository.object.composition.helpers.InvocationMessageContext.proceed(InvocationMessageContext.java:245)
    at object.proxies._1acbd9a953b._EntityProxy251136d71f58a.getMotivatedBy(_EntityProxy251136d71f58a.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.openrdf.repository.object.advisers.PropertyBehaviour.merge(PropertyBehaviour.java:87)
    at object.proxies._1acbd9a953b._EntityProxy251136d71f58a.merge(_EntityProxy251136d71f58a.java)
    at org.openrdf.repository.object.ObjectConnection.addObject(ObjectConnection.java:328)
    at org.openrdf.repository.object.ObjectConnection.addObject(ObjectConnection.java:285)
    at com.github.anno4j.Anno4j.persist(Anno4j.java:165)
    at com.github.anno4j.io.InputOutputTest.testInputAndPersistAnnotation(InputOutputTest.java:69)
```

A similar problem appears in the same test if I do not use an explicit type for targets like

```
 " \"oa:hasTarget\": \"http://www.kernel.org\" \n"
```

which throws the following exception:

```
java.lang.ClassCastException: java.lang.String cannot be cast to com.github.anno4j.model.Target
    at com.github.anno4j.model.AnnotationSupport.getTriples(AnnotationSupport.java:46)
    at object.proxies._1acbd9a953b._EntityProxy251136d71f58a.getTriples(_EntityProxy251136d71f58a.java)
    at com.github.anno4j.io.InputOutputTest.testInputAndPersistAnnotation(InputOutputTest.java:58)
```

As you can see both of the above cases are trying to convert a String to a Motivation or Target class...

**Comment by AEisenkolb** [comment]
Hey @papadako,

I was able to fix the bug with the Motivations (see a158afdf15bdda2bceae3e147d0645fcf3814497). Anyhow, the target problem is not really a bug in anno4j, it´s more a restriction to use a target object, so we wont be able to change.

**Comment by papadako** [comment]
Thank you @AEisenkolb 
So, regarding the target problem anno4j will not support simple oa:Annotations like the one described in section 3.1 of the current  draft https://www.w3.org/TR/annotation-model/

**Comment by schlegel** [comment]
Hello @papadako 
a target or body without a defined rdf:type is currently not possible with Anno4j because we don't have a mapping between the resource and a Java class. A resource without a rdf:type will be mapped to  ResourceObject which can't be casted to Target class or Body class. 

Solution: You could add the rdf:type declaration with e.g. SpecificResource or we could add generic rdf types for body and target e.g. https://github.com/anno4j/ns#Target.

**Comment by papadako** [comment]
Hi @schlegel 
Currently I use  rdf:type in my targets so it is ok with me. I was just mentioning it for the generality of the anno4j approach.
