### ISSUE TITLE
Creation of Objects

### ISSUE THREAD

**Issue by papadako** [anno4j/anno4j#64]
From what I have understood in anno4j v2 we have to use createObject to create the appropriate objects for the annotations. But in its current implementation it creates an intermediate blank node. Take for example the following code that creates a oa:describing motivation

```
        Motivation motivation = anno4j.createObject(Describing.class);
        anno.setMotivatedBy(motivation);
```

These lines will create the following triples:

```
<http://lifewatchgreece.eu/entity/annotations/6bb58859-065c-4edb-8ad8-2d9ad79341cd> <http://www.w3.org/ns/oa#motivatedBy>   <http://lifewatchgreece.eu/entity/annotations/resources/4a1e24bb-9162-491d-8332-f1199172b440>

<http://lifewatchgreece.eu/entity/annotations/resources/a7810bed-74c9-4eff-b8db-9a96dea7b20f>   rdf:type    <http://www.w3.org/ns/oa#describing>
```

 but I guess it would suffice to just create:

```
<http://lifewatchgreece.eu/entity/annotations/6bb58859-065c-4edb-8ad8-2d9ad79341cd> <http://www.w3.org/ns/oa#motivatedBy>   <http://www.w3.org/ns/oa#describing>
```

**Comment by schlegel** [comment]
I think this issue is related to the fix in https://github.com/anno4j/anno4j/issues/63. We mistakenly treated the different Motivations as classes instead of instances of the Motivation class. You can now retrieve Motivation instances with the MotivationFactory and then you have the wished serialisation.

Can we close this issue?

**Comment by papadako** [comment]
Hi @schlegel 
I just rebuilt anno4j using  a branch with both develop and v2-develop merged and this bug does not happen anymore. So I am closing it.

Thanks.

**Comment by papadako** [comment]
Well there is another related problem.
The initial problem of the serialization of the triples is now solved.
But now a new problem has appeared which seems related to https://github.com/anno4j/anno4j/issues/63
If anno is an annotation and anno2 is another annotation, 

```
anno1.setMotivatedBy(anno2.getMotivatedBy());
```

thows the following exception:

```
Caused by: java.lang.ClassCastException: http://www.w3.org/ns/oa#describing cannot be cast to com.github.anno4j.model.Motivation
    at org.openrdf.repository.object.advisers.PropertyBehaviour.intercept(PropertyBehaviour.java:146)
    at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.openrdf.repository.object.composition.helpers.InvocationMessageContext.proceed(InvocationMessageContext.java:245)
    at object.proxies._1acbd9a953b._EntityProxy251136d71f58a.getMotivatedBy(_EntityProxy251136d71f58a.java)
    at object.behaviours.com.github.anno4j.model.AnnotationSupportAbstractClass.getMotivatedBy(AnnotationSupportAbstractClass.java)
    at com.github.anno4j.model.AnnotationSupport.getTriples(AnnotationSupport.java:60)
    at object.proxies._1acbd9a953b._EntityProxy251136d71f58a.getTriples(_EntityProxy251136d71f58a.java)
```

**Comment by AEisenkolb** [comment]
Hey @papadako,

unfortunately I can´t reconstruct your exception. I used the following code:  

 `Annotation annotation = anno4j.createObject(Annotation.class);
        Motivation motivation = MotivationFactory.getBookmarking(anno4j);
        annotation.setMotivatedBy(motivation);

```
    // Persist annotations
    connection.addObject(annotation);

    // Query persisted object
    Annotation an = connection.getObjects(Annotation.class).asList().get(0);

    Annotation annotation1 = anno4j.createObject(Annotation.class);
    annotation1.setMotivatedBy(an.getMotivatedBy());

    assertEquals(annotation.getMotivatedBy(), annotation1.getMotivatedBy());`
```

Any hints?

Best regards
Andreas
